apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: fadiquader-me-tls
spec:
  secretName: fadiquader-me
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: fadiquader.me
  dnsNames:
    - fadiquader.me
    - www.fadiquader.me
  acme:
    config:
      - http01:
          ingressClass: nginx
        domains:
          - fadiquader.me
          - www.fadiquader.me
